name:                AdventOfCode2021
version:             0.1.0.0
github:              "tobiasbengtsson/AdventOfCode2021"
license:             BSD3
author:              "Tobias Bengtsson"
maintainer:          "bo.tobias.bengtsson@gmail.com"
copyright:           "2021 Tobias Bengtsson"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/AdventOfCode2021#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- composition-extra
- containers
- lens
- multiset
- mtl
- split

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - ParallelListComp
    - TupleSections

executables:
  AdventOfCode2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2021
